version: '3.8'

services:
  eureka-server:
    image: analluvias/eureka-server:1.0.0
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - hr-system-docker-compose
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    image: analluvias/api-gateway:1.0.0
    ports:
      - "8765:8765"
    expose:
      - "8765"
    depends_on:
      - eureka-server
    environment:
      - PORT=8765
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system-docker-compose

  user-api:
    image: analluvias/user-api:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system-docker-compose

  payroll-api:
    image: analluvias/payroll-api:1.0.0
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
      - api-gateway
      - user-api
    environment:
      - PORT=8100
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system-docker-compose

networks:
  hr-system-docker-compose:
    driver: bridge